theme: minima

name: Alec Barnard's blog
title: Alec Barnard's blog
description: a blog for security and IT related things

# social links
twitter_username: giguhbit
github_username:  giguhbit
linkedin_username: alec-barnard-lbc
